name: SCHEDULED True

on:
    schedule:
        - cron: '00 18 * * 4'

jobs:
    check-week:
        runs-on: ubuntu-latest
        steps:
            - name: Check if this is the correct week
              run: ./getweek.sh "2024-08-08"

    continue-flow:
        needs: check-week
        runs-on: ubuntu-latest
        if: ${{ success() }} # Continue only if check-week succeeds
        steps:
            - name: Continue if check week is ok
              run: |
                echo "running as expected"
