name: SCHEDULED True

on:
    schedule:
        - cron: '45 20 * * 4'

jobs:
    check-week:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Check if this is the correct week
              run: .github/workflows/getweek.sh "2024-08-15"

    continue-flow:
        needs: check-week
        runs-on: ubuntu-latest
        if: ${{ success() }}
        steps:
            - name: Continue if check week is ok
              run: |
                echo "running as expected"
